dart-lang/ai

.github/ISSUE_TEMPLATE/dart_mcp.md, .github/labeler.yml, .github/workflows/pull_request_label.yml
Additional repo setup for package:dart_mcp:
- add an issue template
- add some PR labelling
---
<details>
- Changes to packages require [corresponding …
=> [dart_mcp] additional repo setup for package:dart_mcp

.github/workflows/dart_mcp.yaml, pkgs/dart_mcp/example/server.dart, pkgs/dart_mcp/lib/src/api.dart
runs test/analyze/format on CI
=> add workflow file for dart_mcp

.gitignore, pkgs/dart_mcp/example/server.dart, pkgs/dart_mcp/lib/src/api.dart, pkgs/dart_mcp/lib/src/server/server.dart, pkgs/dart_mcp/lib/src/util.dart, pkgs/dart_mcp/test/client_and_server_test.dart
With these changes I can successfully hook up an mcp server to Cursor.
=> small bug fixes and tweaks

.github/workflows/dart_tooling_mcp_server.yaml
meant to do this in the last pr
=> add workflow file for dart_tooling_mcp_server

pkgs/dart_mcp/lib/src/client/client.dart
Missed a couple and also added some more in a parallel CL
=> Cleanup: update all methods to use the _sendRequest helper

pkgs/dart_mcp/lib/src/api/api.dart, pkgs/dart_mcp/lib/src/api/resources.dart, pkgs/dart_mcp/test/tools_support_test.dart
Not sure why I didn't just do this earlier, but here it is :)
=> Port Annotation apis and add test exercising them.

pkgs/dart_mcp/lib/src/api/api.dart, pkgs/dart_mcp/lib/src/api/completion.dart, pkgs/dart_mcp/lib/src/api/completions.dart, pkgs/dart_mcp/lib/src/api/initialization.dart, pkgs/dart_mcp/lib/src/client/client.dart, pkgs/dart_mcp/lib/src/server/completions_support.dart, pkgs/dart_mcp/lib/src/server/server.dart, pkgs/dart_mcp/pubspec.yaml, pkgs/dart_mcp/test/completions_test.dart
See https://spec.modelcontextprotocol.io/specification/2025-03-26/server/utilities/completion/
=> Add support for Completions

README.md
Closes https://github.com/dart-lang/ai/issues/18
=> populate package info in README.md

.github/ISSUE_TEMPLATE/dart_tooling_mcp_server.md, .github/labeler.yml
- update repo infra for package:dart_tooling_mcp_server.md
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing). …
=> update repo infra for package:dart_tooling_mcp_server.md

pkgs/dart_tooling_mcp_server/test/test_harness.dart
This more closely mimics the actual setup.
=> disable devtools in `run` commands and move dtd ownership to the FakeEditorExtension 

.gitignore, pkgs/dart_mcp/example/dash_client.dart, pkgs/dart_mcp/example/gemini_client.dart, pkgs/dart_mcp/pubspec.yaml, pkgs/dart_tooling_mcp_server/README.md, pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
Adds a basic command line chat bot client example, accepts stdio servers to connect to as command line arguments.
=> start on an example dash chat client

pkgs/dart_mcp/README.md, pkgs/dart_mcp/pubspec.yaml, pkgs/dart_tooling_mcp_server/pubspec.yaml
misc pubspec and readme cleanups:
- normalize the pubspec contents order
- add markdown badges to the dart_mcp readme
- add a link for issues
---
<details>
- Changes to packages require …
=> misc pubspec and readme cleanups

pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
Also logs other service events
=> add debug logs for when DTD sees Editor.getDebugSessions get registered

pkgs/dart_tooling_mcp_server/README.md
That got auto-landed on approval so this addresses the comments
=> followup to comments on https://github.com/dart-lang/ai/pull/88

pkgs/dart_mcp/CHANGELOG.md, pkgs/dart_mcp/pubspec.yaml
I will probably wait until Monday to actually merge this and tag it
=> Release dart_mcp version 0.2.0

pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart, pkgs/dart_tooling_mcp_server/test/tools/dtd_test.dart
=> Add tool for enabling/disabling the widget selector

.github/workflows/dart_tooling_mcp_server.yaml, pkgs/dart_tooling_mcp_server/test/test_harness.dart
This makes tests run faster, and run without a display.
I am hoping this also reduces some of the flakyness that I still haven't been able to get resolved
=> use flutter-tester device, drop xvfb

pkgs/dart_mcp/README.md
Fixes https://github.com/dart-lang/ai/issues/135
=> fix readme link

pkgs/dart_mcp/example/simple_client.dart
See https://github.com/dart-lang/ai/pull/187 for details
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
=> Update `simple_client.dart` for updated `hello_world` tool name

.github/workflows/dart_mcp_server.yaml, pkgs/dart_mcp_server/pubspec.yaml
This should speed pub get up quite a lot, both locally and on GitHub actions.
=> Pin the SDK git ref and add caching on github actions

GEMINI.md
Created using the `/init` command from Gemini CLI and then asking it to elaborate on a few things
=> add a GEMINI.md file
