dart-lang/ai

- pkgs/dart_mcp/example/server.dart
- pkgs/dart_mcp/lib/src/api.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/test/client_and_server_test.dart
Adds `registerTool` and `unregisterTool` to the ToolSupport mixin, which handles routing, list tools calls, and notifying clients that the tools list has changed (if applicable).
Removes the previous getter indicating whether the server supports notifying about tool changes, because support is built in now.
> Add explicit/opinionated methods for registering tools

- pkgs/dart_mcp/lib/src/api.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/resources_support.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/lib/src/server/tools_support.dart
- pkgs/dart_mcp/lib/src/util.dart
- pkgs/dart_mcp/test/client_and_server_test.dart
- pkgs/dart_mcp/test/resources_support_test.dart
- pkgs/dart_mcp/test/test_utils.dart
- pkgs/dart_mcp/test/tools_support_test.dart
- Adds support for [resources](https://modelcontextprotocol.io/docs/concepts/resources).
- Refactors some things to separate the mixin implementations out into separate files.
- Introduces a TestEnvironment to encapsulate the basic test setup.
> Add basic Resources support, refactor some things

- pkgs/dart_mcp/lib/src/api.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/prompts_support.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/test/prompts_test.dart
- pkgs/dart_mcp/test/test_utils.dart
See https://modelcontextprotocol.io/docs/concepts/prompts
Adds server and client support.
> Add support for prompts

- pkgs/dart_mcp/lib/src/api.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/test/client_and_server_test.dart
See [ping specification](https://spec.modelcontextprotocol.io/specification/2025-03-26/basic/utilities/ping/) and [progess specification](https://spec.modelcontextprotocol.io/specification/2025-03-26/basic/utilities/progress/).
This does not yet support progress notifications for requests from the server to the client - because we don't implement any of those yet. This will come with support for [sampling](https://spec.modelcontextprotocol.io/specification/2025-03-26/client/sampling/) and/or [roots](https://spec.modelcontextprotocol.io/specification/2025-03-26/client/roots/).
I also did a bit of refactoring to extract out a shared `sendRequest` utility - which handles shutting down the progress event streams for a request once the response comes in.
> Support Pings and Progress events

- pkgs/dart_mcp/lib/src/api.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/logging_support.dart
- pkgs/dart_mcp/lib/src/server/resources_support.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/test/logging_test.dart
- pkgs/dart_mcp/test/resources_support_test.dart
See https://spec.modelcontextprotocol.io/specification/2025-03-26/server/utilities/logging/
I also fixed a bug in the resource support - I realized that subscribe/unsubscribe are supposed to return an empty response instead of no response.
Also updated a few of the extension types to take a `MetaWithProgressToken`.
> Add Logging support

- pkgs/dart_mcp/lib/src/api/api.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/tools_support.dart
- pkgs/dart_mcp/lib/src/shared.dart
- pkgs/dart_mcp/test/client_and_server_test.dart
- pkgs/dart_mcp/test/tools_support_test.dart
I noticed that pings didn't work from the inspector, and the latest version of cursor no longer sends an empty Params object for `listTools` (its not required so this is OK).
This handles those situations and adds general support for null request params and null responses.
> support requests with no request params and no response data, handle null params for ping and listTools

- pkgs/dart_mcp/example/client.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/client/roots_support.dart
- pkgs/dart_mcp/test/client_and_server_test.dart
- pkgs/dart_mcp/test/test_utils.dart
This wasn't necessary and it's mostly just awkward, removed the ability to shut down servers by name.
You can close the connections directly by calling `ServerConnection.shutdown`, and that is now the expected way to do it (or by calling `shutdown` on the client to shut down all servers).
> [cleanup] remove the server name argument from the connect methods

- .github/workflows/health.yaml
- .github/workflows/post_summaries.yaml
- .github/workflows/publish.yaml
- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/pubspec.yaml
Uses firehose https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose
Also adds a changelog and removes `publish_to: none` from dart_mcp.
> add health and publish workflows

- pkgs/dart_mcp/example/server.dart
- pkgs/dart_mcp/lib/src/api/api.dart
- pkgs/dart_mcp/lib/src/api/tools.dart
- pkgs/dart_mcp/pubspec.yaml
- pkgs/dart_mcp/test/client_and_server_test.dart
- pkgs/dart_mcp/test/tools_support_test.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
Closes https://github.com/dart-lang/ai/issues/29
This isn't a full implementation of the spec but should cover all the common use cases. You can always just bring your own map here and cast it to the `ObjectSchema` type, if needed.
> Add Schema type for creating input schemas using typed interfaces

- .github/workflows/dart_tooling_mcp_server.yaml
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_tooling_mcp_server/bin/main.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
- pkgs/dart_tooling_mcp_server/test/dart_tooling_mcp_server_test.dart
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
Requires clients to implement "Roots", and creates one analysis context per root.
Then, requests to analyze groups of files can be issued via the "analyze files" command, which requires a root for each group of files.
We also run a file watcher, which is a bit right now because we could be a second or so behind if using a polling watcher. We might want to try and do some sort of "file overlay" situation for other scenarios, passing the file contents to analyze directly.
This is currently based on the input schema branch - I will wait to merge until that is merged and then change the target branch here.
> Add basic analysis support

- pkgs/dart_tooling_mcp_server/test/dart_tooling_mcp_server_test.dart
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
Part of https://github.com/dart-lang/ai/issues/44
- No longer always start up the counter app when starting a debug session, instead we allow you to start a debug session explicitly as needed. Allows for multiple debug sessions to be registered so we can test those workflows in the future.
- Starts an explicit DTD service of our own instead of getting one from `flutter run` or `dart run`. This mimics more the IDE environment, and allows for one connection with multiple apps.
> refactor the test harness to separate out debug sessions

- pkgs/dart_tooling_mcp_server/README.md
- pkgs/dart_tooling_mcp_server/bin/main.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/test/dart_tooling_mcp_server_test.dart
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
Adds a server tool to perform a hot reload against a Flutter app.
> [dart_tooling_mcp_server] Add a hot reload tool

- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dart_cli.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/test/dart_tooling_mcp_server_test.dart
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
- pkgs/dart_tooling_mcp_server/test_fixtures/dart_cli_app/.gitignore
- pkgs/dart_tooling_mcp_server/test_fixtures/dart_cli_app/analysis_options.yaml
- pkgs/dart_tooling_mcp_server/test_fixtures/dart_cli_app/bin/dart_fix.dart
- pkgs/dart_tooling_mcp_server/test_fixtures/dart_cli_app/bin/dart_format.dart
This PR adds tool support for the following Dart CLI tools:
- Running `dart fix` over a set of roots
- Running `dart format` over a set of roots
This PR also adds the directory `test_fixtures/dart_cli_app` which contains Dart scripts for use in tests.
> [dart_tooling_mcp_server] add Dart CLI tool support

- pkgs/dart_mcp/example/dash_client.dart
When determining whether the user agreed to run the tool, we feed their response to gemini and ask it to respond with "y" if they agreed.
Fwiw, I am not sure if this is actually a great idea but it does appear to work 🤣.
It does short circuit for "y" or "yes".
> analyze the sentiment of the response instead of just accepting y/n

- .vscode/launch.json
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
- pkgs/dart_tooling_mcp_server/test/tools/dtd_test.dart
- pkgs/dart_tooling_mcp_server/test_fixtures/counter_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- pkgs/dart_tooling_mcp_server/test_fixtures/counter_app/lib/main.dart
This PR:
- Adds a new tool `get_runtime_errors` to `DartToolingDaemonSupport` for retrieving runtime errors from an app. This method pulls `Flutter.Error` events from the VM service `kExtension` stream as well as any messages to the `kStderr` stream.
- Adds an overflow error to the Flutter test fixture app
- Adds a VS Code launch configuration for easily launching the Flutter test Fixture app
- Makes all tool names use a consistent case (`snake_case`). 
This PR contains some formatting changes. Filed https://github.com/dart-lang/ai/issues/58 to track using a consistent formatting version in this repo.
> [dart_tooling_mcp_server] Add a tool for getting runtime errors

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/test/tools/dtd_test.dart
This PR adds a tool that gets the widget tree for a running Flutter app. In its current form, this tool calls the `ext.flutter.inspector.getRootWidgetTree` service extensions with the following parameters:
```
'groupName': groupId,
'isSummaryTree': 'true',
'withPreviews': 'true',
'fullDetails': 'true',
```
This will return Widgets that were added to the tree from the user's code (it will not contain implementation widgets). @elliette what do you think of these default values? 
Example response:
```
{description: [root], type: _ElementDiagnosticableTreeNode, style: dense, hasChildren: true, allowWrap: false, summaryTree: true, valueId: inspector-83, locationId: 0, creationLocation: {file: file:///Users/kenzieschmoll/develop/flutter/packages/flutter/lib/src/widgets/binding.dart, line: 1331, …
```
> [dart_tooling_mcp_server] add `get_widget_tree` tool

- pkgs/dart_mcp/example/dash_client.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
Instead of failing the whole connection, we just disable analysis and log warnings.
> handle missing roots capability better

- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dart_cli.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
- pkgs/dart_tooling_mcp_server/test/tools/dtd_test.dart
- pkgs/dart_tooling_mcp_server/test_fixtures/counter_app/lib/main.dart
This PR:
- persists active VM service objects so that we do not need to recreate them for each DTD tool call
- cleans up a stream subscription disposal for the hot reload command (review with hide whitespace diffs)
> [dart_tooling_mcp_server] Persist VmService objects

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/README.md
- pkgs/dart_mcp/example/client.dart
- pkgs/dart_mcp/example/dash_client.dart
- pkgs/dart_mcp/lib/src/api/api.dart
- pkgs/dart_mcp/lib/src/api/completions.dart
- pkgs/dart_mcp/lib/src/api/initialization.dart
- pkgs/dart_mcp/lib/src/api/prompts.dart
- pkgs/dart_mcp/lib/src/api/resources.dart
- pkgs/dart_mcp/lib/src/api/tools.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/pubspec.yaml
- pkgs/dart_mcp/test/api_test.dart
- pkgs/dart_mcp/test/client_and_server_test.dart
- pkgs/dart_mcp/test/test_utils.dart
- pkgs/dart_mcp/test/tools_support_test.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
I had already implemented one portion of this by accident apparently (completions support).
Adds version negotiation and a few other small breaking changes since I wanted to make a breaking change anyways to convert the protocol version to an enum.
> Update spec to 2025-03-26

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/test/tools/dtd_test.dart
This PR adds a tool that gets the selected widget from the Widget Inspector for a running Flutter app. In its current form, this tool calls the `ext.flutter.inspector.getSelectedSummaryWidget` service extension. I opted to use `getSelectedSummaryWidget` instead of `getSelectedWidget` because this tool will likely be useful in the context of the user's code.
> [dart_tooling_mcp_server] add tool for getting the selected widget

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dart_cli.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/lib/src/utils/process_manager.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
- pkgs/dart_tooling_mcp_server/test/tools/dart_cli_test.dart
This allows us to not duplicate testing that is already done for CLI tools this server is calling into (like the Dart CLI for example).
> Add `ProcessManagerSupport` mixin to make CLI command end points more testable

- pkgs/dart_mcp/example/dash_client.dart
- pkgs/dart_tooling_mcp_server/lib/src/lsp/wire_format.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
- pkgs/dart_tooling_mcp_server/test/tools/analyzer_test.dart
- Use `dart language-server` for errors, file watching, etc.
- Drop analyzer dependency.
- Depends on language_server_protocol package from the SDK using a git dependency for now:
- We can fix this by moving into the SDK
- Or publishing language_server_protocol
- The tool now just always returns all errors for all known workspaces.
- Errors are returned in a structured format right now instead of as a human readable string.
- We might want to steal some code from analyzer/DartCode etc to get a human readable string going.
- Or if this is just for AI input, structured may even be better.
In the future, we might try to use the DTD connection to talk, which won't change this code too much. But right now DTD has very limited support (read/write properties).
Closes …
> Update analyze tool to use LSP, simplify tool

- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/test/tools/analyzer_test.dart
This allows you to ask things like "Tell me about <class-name> in my project" and it will tell you where it is located.
Follow on features will allow for looking up more detailed information about the symbol such as its doc comments and API.
> implement a tool to resolve workspace symbols based on a query

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dart_cli.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/pub.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_tooling_mcp_server/test/tools/dart_cli_test.dart
- pkgs/dart_tooling_mcp_server/test/tools/pub_test.dart
This refactors the pub support to be part of its own support mixin instead of being part of the Dart CLI tools mixin. This is because once https://github.com/dart-lang/ai/issues/81 is resolved, this tool won't necessarily be using the Dart CLI or the Flutter CLI, but may use either.
This PR pulls out a utility method `runCommandInRoots` from the Dart CLI support mixin for reuse.
> Break pub tools out into their own support mixin

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/server/roots_tracking_support.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/test/roots_tracking_support_test.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dart_cli.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
This mixin will be used by anything that wants to look at what the current roots are, so we can share that logic across them.
Likely we will want to add this to various other tools (like the command line tools).
> Add a RootsTrackingSupport mixin for servers, use it from DartAnalyzerSupport

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/test/tools/dtd_test.dart
This allows the agent to only see new errors, otherwise old errors are repeatedly given. Gemini 2.5 pro at least does appear to be smart enough to handle this automatically.
> Add support for `since` argument to `runtimeErrors` tool

- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/test/tools/analyzer_test.dart
Closes https://github.com/dart-lang/ai/issues/80
> require roots to be set for analyzer tools

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/server/resources_support.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/pubspec.yaml
- pkgs/dart_mcp/test/resources_support_test.dart
This is in anticipation of potentially modeling runtime errors as resources, so they might be updated often. But it is in general a good practice to throttle these.
> Add throttling for resource notifications

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/api/initialization.dart
Fix for https://github.com/dart-lang/ai/issues/97
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that …
> Making `instructions` optional.

- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/pubspec.yaml
- pkgs/dart_mcp/test/client_and_server_test.dart
Related to https://github.com/dart-lang/ai/issues/96
- Tests the current behavior, ensures we aren't leaking exceptions beyond what is expected.
- Also documents explicitly the behavior in initialize to encourage exception handling, and helping you to debug.
> add test for server closing early to validate behavior

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/server/server.dart
This is a continuation of https://github.com/dart-lang/ai/pull/98
PTAL @jakemac53 
---
<details>
- Changes to packages require [corresponding …
> Continue making `instructions` optional.

- pkgs/dart_tooling_mcp_server/README.md
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_tooling_mcp_server/lib/src/utils/constants.dart
- pkgs/dart_tooling_mcp_server/test/tools/analyzer_test.dart
This forwards directly to the [LSP signature help](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp) functionality.
Allows requesting information about the signature of some API being _used_ at a specific cursor location.
**Note**: Does not seem to give useful information if the location is a _definition_ site (such as one returned by a workspace_symbol lookup). But this looks like it is by design probably.
> add signature_help tool

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/example/workflow_client.dart
- pkgs/dart_mcp/pubspec.yaml
- pkgs/dart_tooling_mcp_server/lib/src/utils/cli_utils.dart
Makes the bot more interactive and also gives us a sense of total input/output token usage [Screen recording 2025-05-05 9.24.57 AM.webm](https://github.com/user-attachments/assets/993729bf-889a-485f-b295-9be52ca0e242)
Also makes a small fix to the tooling server so it is compatible again (it had lost compatibility due to a recent change which added a list schema with no items schema, which seems to be required for gemini tools).
> show thinking text and input/output token usage

- pkgs/dart_mcp/example/file_system_server.dart
- pkgs/dart_mcp/example/workflow_client.dart
- pkgs/dart_mcp/pubspec.yaml
This is useful for testing the workflow client with more complicated flows to give it file system access, without needing to depend on a third party server for that.
> add basic file system server example

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dash_cli.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/pub.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_tooling_mcp_server/lib/src/utils/file_system.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
- pkgs/dart_tooling_mcp_server/test/tools/analyzer_test.dart
- pkgs/dart_tooling_mcp_server/test/tools/dart_cli_test.dart
- pkgs/dart_tooling_mcp_server/test/tools/pub_test.dart
- pkgs/dart_tooling_mcp_server/test/utils/cli_utils_test.dart
- pkgs/dart_tooling_mcp_server/test_fixtures/dart_cli_app/pubspec.yaml
- Rename `DartCliSupport` to `DashCliSupport`
- Add support for choosing the command to run based on the root it is ran in
- Defaults to project detection, calling `flutter` or `dart` as appropriate.
- Updated the dart only commands to explicitly use `dart` always
- Adds a tool for running tests, which requires this support.
TODO: Add support for some `test` command arguments such as `--name`, and possibly platform or other arguments. We may just want to allow general arguments.
> add a test command and project detection

- pkgs/dart_mcp/example/workflow_client.dart
This significantly reduces token usage by continuously cleaning up history after each task.
The model decides when it is done and outputs the text 'workflow completed' which summarizes what was done, and only this summary is then retained in the context.
- Also includes some unrelated cleanups that Gemini did, although I cleaned up a lot of those there were some worth keeping.
> Clear context after completing a workflow

- pkgs/dart_tooling_mcp_server/README.md
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/test/tools/analyzer_test.dart
An additional tool to be used to get information for a cursor position, forwards directly to the LSP hover support https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover.
> add hover tool support

- pkgs/dart_tooling_mcp_server/README.md
- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
- pkgs/dart_tooling_mcp_server/test/tools/dtd_test.dart
Similar to the selected widget tool this should help the AI get some context as to what the user is talking about.
Just directly forwards the last event received from DTD.
> Add a tool to get the active cursor location

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/shared.dart
- pkgs/dart_mcp/test/client_and_server_test.dart
This fixes a bug in notification handling where if the parameters were left off, as in:
```json
{"jsonrpc":"2.0","method":"notifications/initialized"}
```
instead of:
```json
{"jsonrpc":"2.0","method":"notifications/initialized", "params": {}}
```
A type error would get silently ignored and the notification would never be received.
> Fix notification bug where null parameters caused type error

- pkgs/dart_mcp/example/file_system_server.dart
Previously this would call `_checkAllowedPath`, see that it was a valid Uri, and then just read the path relative to the current working directory instead of the root directory.
Also added a check that only one root is configured when using relative paths.
> fix file system server to look up relative paths in the proper root

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
This should resolve the flakyness in tests.
Other VM service interactions already handle this better because they are scoped to an RPC request, and will just return an appropriate error for that request. But we set up these error listeners out of band and so the exceptions are not handled if we fail to listen to the streams due to the connection being closed.
> handle failing to listen to vm service streams during startup

- pkgs/dart_tooling_mcp_server/README.md
- pkgs/dart_tooling_mcp_server/test/test_harness.dart
Also updates the readme with pub global activate instructions as opposed to suggesting you must use the compiled exe. This makes development a lot easier (don't have to recompile manually all the time).
Closes https://github.com/dart-lang/ai/issues/44
> use `dart pub run` for the server to speed up tests. 

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/example/client.dart
- pkgs/dart_mcp/example/workflow_client.dart
- pkgs/dart_mcp/lib/src/api/initialization.dart
- pkgs/dart_mcp/lib/src/client/client.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_mcp/lib/src/shared.dart
Adds `--help`, `--log`, and `--model` flags to the workflow example and fixes a problem where the examples would only connect to servers with the latest protocol version (instead of any supported version).
> Add some flags to example, fix version issue

- pkgs/dart_tooling_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
Errors will not be as good for invalid pubspecs.
In preparation for moving into the Dart SDK, where dependencies are more restricted.
> drop pubspec-parse, use yaml instead

- pkgs/dart_tooling_mcp_server/lib/src/mixins/dtd.dart
This now gives a ParallelWaitError so the catch wasn't catching it, I just dropped the specific kind of error, we don't want anything from here to leak out and we are logging them.
> fix error handling around stream listeners

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/server/roots_tracking_support.dart
- pkgs/dart_mcp/lib/src/server/server.dart
- pkgs/dart_tooling_mcp_server/bin/main.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_tooling_mcp_server/lib/src/mixins/roots_fallback_support.dart
- pkgs/dart_tooling_mcp_server/lib/src/server.dart
- pkgs/dart_tooling_mcp_server/lib/src/utils/constants.dart
- pkgs/dart_tooling_mcp_server/pubspec.yaml
- pkgs/dart_tooling_mcp_server/test/tools/roots_fallback_support_test.dart
This mixin can be used to conditionally add `addRoots` and `removeRoots` tools, when the client doesn't support roots.
It overrides all the `RootsTrackingSupport` functionality as well as the `listRoots` method, to use the custom behavior instead.
Also adds a flag to force this fallback mode to the server, which is required for some clients who claim to support roots but do not actually (like cursor).
Closes https://github.com/dart-lang/ai/issues/111
> Add RootsFallbackSupport mixin

- .github/workflows/pull_request_label.yml
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_mcp_server/test/tools/dtd_test.dart
Fixes https://github.com/dart-lang/ai/issues/134
> Limit the tokens returned by the runtime errors tool/resource

- pkgs/dart_mcp_server/lib/src/mixins/pub_dev_search.dart
- pkgs/dart_mcp_server/test/tools/pub_dev_search_test.dart
Closes https://github.com/dart-lang/ai/issues/145
I did some testing myself and we easily get >10k tokens added to the context for a single query which is definitely too much for the value provided here.
> remove qualifiedNames from the pub dev api search

- pkgs/dart_mcp_server/bin/main.dart
- pkgs/dart_mcp_server/lib/dart_mcp_server.dart
- pkgs/dart_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_mcp_server/lib/src/mixins/dash_cli.dart
- pkgs/dart_mcp_server/lib/src/mixins/pub.dart
- pkgs/dart_mcp_server/lib/src/server.dart
- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/lib/src/utils/sdk.dart
- pkgs/dart_mcp_server/test/test_harness.dart
- pkgs/dart_mcp_server/test/tools/dart_cli_test.dart
- pkgs/dart_mcp_server/test/tools/pub_test.dart
- pkgs/dart_mcp_server/test/utils/cli_utils_test.dart
Closes https://github.com/dart-lang/ai/issues/33
Adds --dart-sdk and --flutter-sdk arguments to the CLI, falling back on DART_SDK and FLUTTER_SDK environment variables, and finally `Platform.resolvedExecutable`.
The flutter SDK will also be looked up relative to the Dart SDK, if a location is not given by command line arg or environment.
> Invoke dart/flutter in a more robust way

- pkgs/dart_mcp_server/lib/src/mixins/dash_cli.dart
- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/lib/src/utils/constants.dart
- pkgs/dart_mcp_server/lib/src/utils/process_manager.dart
- pkgs/dart_mcp_server/test/tools/dart_cli_test.dart
This adds support for the --platform and --empty arguments of the Flutter CLI tool, so that the LLM can create projects for specific platforms, and will by default create projects without extra boilerplate, etc.
- Added tests for the two new options.
> Add the --platform and --empty arguments to the flutter create tool

- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/test/utils/cli_utils_test.dart
You can't set a working dir if it doesn't exist, this ensures the dir does actually exist. LLMs like to sometimes set a root that is a subdirectory of an actual root, which is generally fine, but we need to make sure to create it.
> create the working dir if it doesn't exist

- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/pubspec.yaml
- pkgs/dart_mcp_server/test/utils/cli_utils_test.dart
Instead of using `isWithin` and also checking for exact equality, we compare the scheme/authority, and then compare the canonicalized paths.
> Be more flexible about roots by comparing canonicalized paths

- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/test/tools/pub_test.dart
Changed `commandForRoot` and `inferProjectRoot` to take a String (the root uri) instead of a Root or support this.
> pass the provided root instead of the resolved root for project type detection

- .github/workflows/dart_mcp.yaml
- .github/workflows/dart_mcp_server.yaml
- pkgs/dart_mcp_server/lib/src/utils/sdk.dart
- pkgs/dart_mcp_server/test/test_harness.dart
- pkgs/dart_mcp_server/test/tools/analyzer_test.dart
- pkgs/dart_mcp_server/test/tools/dart_cli_test.dart
- pkgs/dart_mcp_server/test/tools/dtd_test.dart
- pkgs/dart_mcp_server/test/tools/pub_test.dart
Closes https://github.com/dart-lang/ai/issues/32
I believe this should just work now that we are using headless flutter
Initially also added macos tests but those bots tend to wait queued for a long time, so I have removed them.
> run tests on windows, fix executable paths for dart/flutter

- pkgs/dart_mcp_server/bin/main.dart
- pkgs/dart_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_mcp_server/lib/src/mixins/dash_cli.dart
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_mcp_server/lib/src/mixins/pub_dev_search.dart
- pkgs/dart_mcp_server/lib/src/mixins/roots_fallback_support.dart
- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/pubspec.yaml
- pkgs/dart_mcp_server/test/test_harness.dart
- pkgs/dart_mcp_server/test/tools/dtd_test.dart
- pkgs/dart_mcp_server/test/tools/pub_dev_search_test.dart
- pkgs/dart_mcp_server/test/tools/pub_test.dart
The code will only ship with newer SDKs but keep compatibility for
easier testing from source with older SDKs.
Remove use of null aware elements.
> Retain compatibility with 3.7 SDKs

- pkgs/dart_mcp_server/CHANGELOG.md
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_mcp_server/pubspec.yaml
Closes https://github.com/dart-lang/ai/issues/177
> improve tool description for the dtd connection tool and improve error messages

- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
> fix cruft in description

- pkgs/dart_mcp_server/test/dart_tooling_mcp_server_test.dart
Seeing a lot of flakes on windows for this test, adding some retry logic for deleting the file and also reading from it should make it more reliable.
> make the log file test less flaky by retrying deletes and reads

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/api/completions.dart
- pkgs/dart_mcp/lib/src/api/initialization.dart
- pkgs/dart_mcp/lib/src/api/logging.dart
- pkgs/dart_mcp/lib/src/api/prompts.dart
- pkgs/dart_mcp/lib/src/api/resources.dart
- pkgs/dart_mcp/lib/src/api/roots.dart
- pkgs/dart_mcp/lib/src/api/sampling.dart
- pkgs/dart_mcp/lib/src/api/tools.dart
- pkgs/dart_mcp/lib/src/shared.dart
- pkgs/dart_mcp/pubspec.yaml
- pkgs/dart_mcp/test/api/api_test.dart
This adds error checking and throws `ArgumentError` for `Request` subclasses which have required fields.  This is because in `shared.dart`, in `registerRequestHandler`, it casts the argument's value to a Map<String, Object?>, but it doesn't do any argument checking because creating those request objects don't go through the constructors, they are just cast:
```dart
return impl((p.value as Map?)?.cast<String, Object?>() as T);
```
So I added error checking to all of the accessors for required members of `Request` objects, so that when they are accessed they will throw.
I ran across this when a client tried to send a malformed initialization request that didn't include capabilities, and the stack trace it sent was less than helpful.  This will at least send clearer errors.
- Added a test to …
> Add error checks for accessing Request members

- .github/workflows/mcp_examples.yaml
- add a github workflow for mcp_examplee/
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many …
> add a github workflow for mcp_examples/

- pkgs/dart_mcp_server/CHANGELOG.md
- pkgs/dart_mcp_server/README.md
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_mcp_server/lib/src/server.dart
- pkgs/dart_mcp_server/test/test_harness.dart
- pkgs/dart_mcp_server/test/tools/dtd_test.dart
Disabling due to https://github.com/flutter/flutter/issues/170357 - this only works today by default on the desktop environment.
We could fall back on full device screenshots but are holding off on that for now as we have to evaluate some extra potential privacy concerns with exposing the entire screen as opposed to just the flutter drawn pixels.
> disable the screenshots tool by default

- pkgs/dart_mcp_server/lib/arg_parser.dart
- pkgs/dart_mcp_server/lib/src/arg_parser.dart
- pkgs/dart_mcp_server/lib/src/server.dart
The dart tool actually wants to set a few variables and needs to exclude the help command otherwise it is duplicated.
> move static argParser variable to a createArgParser function

- pkgs/dart_mcp_server/pubspec.yaml
- pkgs/dart_mcp_server/test/arg_parser_test.dart
> add a test that the arg parser library only depends on package:args

- pkgs/dart_mcp_server/README.md
@dantup this addresses your comments on https://github.com/dart-lang/ai/pull/201#discussion_r2172757237. Please let me know if there are other changes you'd like me to make to the docs.
> Remove VS Code mcp instructions in favor of Dart-Code setting.

- pkgs/dart_mcp_server/CHANGELOG.md
- pkgs/dart_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_mcp_server/lib/src/mixins/dash_cli.dart
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_mcp_server/lib/src/mixins/pub.dart
- pkgs/dart_mcp_server/lib/src/mixins/pub_dev_search.dart
- pkgs/dart_mcp_server/lib/src/server.dart
- pkgs/dart_mcp_server/lib/src/utils/analytics.dart
- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/test/dart_tooling_mcp_server_test.dart
- pkgs/dart_mcp_server/test/tools/pub_dev_search_test.dart
This should help us to understand why tool calls fail, instead of just seeing that they failed.
In particular for tests as an example, we can discard the ones that fail due to a non-zero exit code.
> Add failure reasons to tool call analytics events

- pkgs/dart_mcp_server/CHANGELOG.md
- pkgs/dart_mcp_server/lib/src/mixins/pub.dart
- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
- pkgs/dart_mcp_server/lib/src/utils/constants.dart
- pkgs/dart_mcp_server/test/tools/pub_test.dart
This allows `pub add` and `pub remove` to take multiple packages at once, and provides guidance for dev dependencies.
- Fixes https://github.com/dart-lang/ai/issues/225
- Fixes https://github.com/dart-lang/ai/issues/77
- Modified tests for multiple package names.
> Allow multiple package arguments to pub commands

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/example/elicitations_client.dart
- pkgs/dart_mcp/example/elicitations_server.dart
- pkgs/dart_mcp/example/tools_client.dart
- pkgs/dart_mcp/lib/src/api/elicitation.dart
- pkgs/dart_mcp/lib/src/api/initialization.dart
More work towards https://github.com/dart-lang/ai/issues/220
> add elicitation example, fix some issues with the elicitation APIs

- pkgs/dart_mcp/example/sampling_client.dart
- pkgs/dart_mcp/example/sampling_server.dart
Towards https://github.com/dart-lang/ai/issues/220
> add a sampling example

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/lib/src/client/elicitation_support.dart
This extra type wasn't necessary - now this follows the pattern of the other support mixins, just defining the abstract method on the mixin itself.
> Deprecate the WithElicitationhandler interface

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/README.md
- pkgs/dart_mcp/pubspec.yaml
Bug fixes, improved examples, and some deprecated APIs and minor cleanup.
> release dart_mcp 0.3.1

- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
These are supposed to be just booleans, but represented as strings (who knows why...)
> fix the firstMatchOnly and matchRoot schemas to be booleans

- mcp_examples/bin/workflow_client.dart
- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/example/elicitations_client.dart
- pkgs/dart_mcp/example/elicitations_server.dart
- pkgs/dart_mcp/lib/src/api/elicitation.dart
- pkgs/dart_mcp/lib/src/api/tools.dart
- pkgs/dart_mcp/pubspec.yaml
- pkgs/dart_mcp/test/api/tools_test.dart
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_mcp_server/pubspec.yaml
Enums are supposed to be represented as the "string" type with an "enum" entry. This was breaking Gemini CLI with the recent addition of some enum types for the flutter driver tool.
> Deprecate EnumSchema and JsonType.enumeration

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/pubspec.yaml
This pushes out the enum changes which the Dart MCP server relies on to work with Gemini CLI (and probably other agents).
> release dart_mcp version 0.3.2

- pkgs/dart_mcp_server/CHANGELOG.md
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
- pkgs/dart_mcp_server/test/test_harness.dart
- pkgs/dart_mcp_server/test/tools/analyzer_test.dart
- pkgs/dart_mcp_server/test/tools/dart_cli_test.dart
- pkgs/dart_mcp_server/test/tools/dtd_test.dart
- pkgs/dart_mcp_server/test/tools/pub_dev_search_test.dart
- pkgs/dart_mcp_server/test/tools/pub_test.dart
- All the flutter driver arguments are actually supposed to be string values so this fixes those schemas
- Change the widget tree to not be the summary by default - summary trees hide nested text widgets which makes it hard for the LLM to find things. This can be explicitly toggled on though.
- Added support for the flutter driver screenshot command, which works on simulators 🥳 
- Rework tests a bit so there is a helper for normal tool calls without retries
- Removed the `get_layer_tree` and `get_render_tree` flutter driver commands for now - I don't see these ever being used.
> Flutter driver updates, add screenshot support back

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp_server/lib/src/utils/cli_utils.dart
Based on this suggestion from @DanTup https://github.com/dart-lang/tools/pull/2138#issuecomment-3133627598
> only run in shell when on windows and running a .bat file

- pkgs/dart_mcp/CHANGELOG.md
- pkgs/dart_mcp/example/tools_client.dart
- pkgs/dart_mcp/example/tools_server.dart
- pkgs/dart_mcp/pubspec.yaml
Initially created this just for testing Gemini CLI support for progress tokens, but it makes sense to land.
> add an example of using progress tokens to the tools example

- pkgs/dart_mcp_server/CHANGELOG.md
- pkgs/dart_mcp_server/lib/src/mixins/dtd.dart
This fixes an issue where hot reload would fail saying that the stream was already subscribed. It fixes the problem by centralizing the method name lookup so that `hotReload` doesn't have to subscribe to the stream itself, and the `_AppListener` can be the single manager of stream listeners.
-  Fixes #290
> Fix hot reload subscription problem

- pkgs/dart_mcp_server/CHANGELOG.md
- pkgs/dart_mcp_server/README.md
- pkgs/dart_mcp_server/lib/src/mixins/analyzer.dart
- pkgs/dart_mcp_server/lib/src/mixins/flutter_launcher.dart
- pkgs/dart_mcp_server/lib/src/server.dart
- pkgs/dart_mcp_server/test/tools/flutter_launcher_test.dart
- pkgs/dart_mcp_server/tool/update_readme.dart
This moves the tools from the Flutter Gemini CLI extension's MCP server to this server, since they are generally useful.
Also updated the `update_readme.dart` tool to sort the tools by name in the `README.md` list.
- Added tests and a `MockProcessManager` for mocking commands so that they don't actually try to run.
> Add the Flutter launcher tools
